<?php

/**
 * Created by PhpStorm.
 * User: russellstather
 * Date: 05/09/15
 * Time: 22:51
 */

require_once __DIR__ . '/../configure.php';

/**
 * @backupGlobals disabled
 */
class UserControllerTest extends PHPUnit_Framework_TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }



    public function testMe()
    {
        $c = new \com\readysteadyrainbow\controllers\UserController("addUser");
        $m = new \com\readysteadyrainbow\models\AddUserModel();
        $m->email = "fred@fred.com";
        $c->addUser($m);
        $a = 1;
    }
}
